use BusScheduleDB
go

delete StudentTransportation
go

insert StudentTransportation(LastName, FirstName, Class, Address, Stop, AMRoute, PMRoute, FridayRoute)
select 'Lincoln', 'Abraham', '4-101', '19th ave', 'corner 45th st',	'A-JKL', 'P-JKL', 'F-JKL'
union select 'Jackson',	'Andrew', '8-100', '13th ave', 'corner 50th st', 'A-ABC', 'P-JKL', 'F-GHI'
union select 'Johnson', 'Andrew', '4-101', '18th ave', 'corner 48th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Obama', 'Barack', '8-104', '17th ave', 'corner 39th st', 'A-ABC', 'P-GHI', 'F-GHI'
union select 'Harrison', 'Benjamin', '4-102', '15th ave', 'corner 54th st',	'A-DEF', 'P-GHI', 'F-DEF'
union select 'Coolidge', 'Calvin', '6-102', '13th ave', 'corner 45th st', 'A-DEF', 'P-ABC', 'F-ABC'
union select 'Arthur', 'Chester', '4-102',	'13th ave', 'corner 54th st', 'A-GHI', 'P-ABC',	'F-ABC'
union select 'Trump', 'Donald', '4-104', '18th ave', 'corner 39th st', 'A-JKL',	'P-JKL', 'F-JKL'
union select 'Eisenhower', 'Dwight David', '8-103',	'17th ave', 'corner 45th st', 'A-GHI', 'P-JKL',	'F-GHI'
union select 'Pierce', 'Franklin', '4-101',	'19th ave', 'corner 45th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Roosevelt', 'Franklin Delano', '5-103', '15th ave', 'corner 45th st',	'A-DEF', 'P-ABC', 'F-DEF'
union select 'Washington', 'George', '8-100', '15th ave', 'corner 46th st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Bush', 'George H. W.', '4-104', '14th ave', 'corner 39th st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Bush', 'George W.', '8-104', '16th ave', 'corner 39th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Ford', 'Gerald R.', '3-103', '11th ave', 'corner 39th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Cleveland', 'Grover', '4-102', '14th ave', 'corner 54th st', 'A-DEF', 'P-DEF', 'F-ABC'
union select 'Cleveland', 'Grover', '4-102', '16th ave', 'corner 54th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Truman', 'Harry S', '8-103', '16th ave', 'corner 45th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Hoover', 'Herbert C.', '4-103', '14th ave', 'corner 45th st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Garfield', 'James', '0-101', '12th ave', 'corner 54th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Madison', 'James', '8-100', '15th ave', 'corner 46th st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Monroe', 'James', '8-100', '16th ave', 'corner 46th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Buchanan', 'James', '4-101', '18th ave', 'corner 45th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Carter', 'James Earl', '4-103', '12th ave', 'corner 39th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Polk', 'James K.', '4-101', '15th ave', 'corner 49th st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Biden', 'Joe', '6-104', '19th ave', 'corner 39th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Tyler', 'John', '4-100', '14th ave', 'corner 52nd st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Adams', 'John', '4-100', '16th ave', 'corner 46th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Kennedy', 'John Fitzgerald', '2-103', '18th ave', 'corner 45th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Adams', 'John Quincy', '4-100', '17th ave', 'corner 46th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Johnson', 'Lyndon Baines', '6-103', '19th ave', 'corner 44th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'van Buren', 'Martin', '4-100', '13th ave', 'corner 50th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Fillmore', 'Millard', '3-101', '18th ave', 'corner 45th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Nixon', 'Richard Milhous', '5-103', '20th ave', 'corner 45th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Reagan', 'Ronald Wilson', '8-103', '13th ave', 'corner 39th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Hayes', 'Rutherford', '4-101', '12th ave', 'corner 54th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Roosevelt', 'Theodore', '8-102', '18th ave', 'corner 54th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Jefferson', 'Thomas', '8-100', '17th ave', 'corner 46th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Grant', 'Ulysses S.', '8-101', '19th ave', 'corner 48th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Harding', 'Warren', '2-102', '12th ave', 'corner 45th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'McKinley', 'William', '4-102', '17th ave', 'corner 54th st', 'A-GHI', 'P-GHI', 'F-GHI'
union select 'Taft', 'William', '4-102', '19th ave', 'corner 54th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Harrison', 'William H.', '7-100', '13th ave', 'corner 50th st', 'A-ABC', 'P-ABC', 'F-ABC'
union select 'Clinton', 'William Jefferson', '8-104', '15th ave', 'corner 39th st', 'A-DEF', 'P-DEF', 'F-DEF'
union select 'Wilson', 'Woodrow', '8-102', '20th ave', 'corner 54th st', 'A-JKL', 'P-JKL', 'F-JKL'
union select 'Taylor', 'Zachary', '1-101', '16th ave', 'corner 50th st', 'A-GHI', 'P-GHI', 'F-GHI'

